apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-kafka.fullname" . }}-headless
  labels:
    app: {{ template "cp-kafka.name" . }}
    chart: {{ template "cp-kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.headlessService.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  ports:
    - port: 9092
      name: broker
      {{- if and (or (eq .Values.headlessService.serviceType "NodePort") (eq .Values.headlessService.serviceType "LoadBalancer")) (not (empty .Values.headlessService.nodePort)) }}
      nodePort: {{ .Values.headlessService.nodePort }}
      {{- else if eq .Values.headlessService.serviceType "ClusterIP" }}
      nodePort: null
      {{- end }}
  clusterIP: null
  selector:
    app: {{ template "cp-kafka.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.headlessService.serviceType }}
