apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-kafka.fullname" . }}-headless
  labels:
    app: {{ template "cp-kafka.name" . }}
    chart: {{ template "cp-kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- if .Values.headlessService.annotations }}
  {{- include "common.tplvalues.render" (dict "value" .Values.headlessService.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: 9092
      name: broker
  clusterIP: None
  selector:
    app: {{ template "cp-kafka.name" . }}
    release: {{ .Release.Name }}